# Example config.yaml

####################################### crawling #######################################

sagepub_crawling:
  START_URL:
    - "https://journals.sagepub.com/toc/examplejournal/vol/issue"
  STOP_YEAR:
    - 2023
  OUTPUT_CSV:
    - "./output/sagepub/meta.csv"
  PDF_DIR:
    - "./output/sagepub/pdfs"

jstage_crawling:
  ROOT_URLS:
    - "https://www.jstage.jst.go.jp/browse/example/1/_contents/-char/en"
    - "https://www.jstage.jst.go.jp/browse/example/2/_contents/-char/en"
  STOP_YEAR:
    - 2023
  OUTPUT_CSV:
    - "./output/jstage/meta.csv"
  PDF_DIR:
    - "./output/jstage/pdfs"
  MAX_NAME_LEN:
    - 50

wiley_crawling:
  ROOT_URLS:
    - "https://onlinelibrary.wiley.com/loi/examplejournal/year/2023"
    - "https://onlinelibrary.wiley.com/loi/examplejournal/year/2024"
  STOP_YEAR:
    - 2023
  OUTPUT_CSV:
    - "./output/wiley/meta.csv"
  PDF_DIR:
    - "./output/wiley/pdfs"
  MAX_NAME_LEN:
    - 50

aami_crawling:
  ROOT_URLS:
    - "https://array.aami.org/loi/example/group/d2020.y2023"
    - "https://array.aami.org/loi/example/group/d2020.y2024"
  STOP_YEAR:
    - 2023
  OUTPUT_CSV:
    - "./output/aami/meta.csv"
  PDF_DIR:
    - "./output/aami/pdfs"
  MAX_NAME_LEN:
    - 50

springer_crawling:
  ROOT_URLS:
    - "https://link.springer.com/journal/example/volumes-and-issues/12-1"
    - "https://link.springer.com/journal/example/volumes-and-issues/11-1"
  STOP_YEAR:
    - 2023
  OUTPUT_CSV:
    - "./output/springer/meta.csv"
  PDF_DIR:
    - "./output/springer/pdfs"
  MAX_NAME_LEN:
    - 50

####################################### export excel #######################################

excel_creator:
  CSV_PATH:
    - "./output/meta.csv"
  ROOT_DIR:
    - "./output"
  OUTPUT_XLSX:
    - "./output/meta.xlsx"
  SRC_COLUMN:
    - "FileName"
  MATCH_CUTOFF:
    - 0.7

####################################### url to csv #######################################

urls2csv:
  INPUT_DIR:
    - "./input/urls"
  OUTPUT_DIR:
    - "./output/csvs"
  URL_FILE_PATTERN:
    - "_filetype_pdf_"

####################################### pdf downloader #######################################

aria2_download:
  INPUT_DIR:
    - "./output/csvs"
  OUTPUT_DIR:
    - "./output/pdfs"

####################################### video downloader #######################################

yt_dlp_download:
  INPUT_DIR:
    - "./input/video_csvs"
  OUTPUT_DIR:
    - "./output/videos"
  YT_DLP_CMD:
    - "yt-dlp"
  YT_DLP_OPTS:
    - "--no-playlist"
    - "--retries=3"
    - "--rate-limit=500K"
    - "--user-agent=Mozilla/5.0"

####################################### final stage #######################################

scan_folder:
  INPUT_DIR:
    - "./output"
  LANG:
    - EN
    - CN
    - RU
  FILE_TYPE:
    - pdf
    - video
